spring.datasource.url=jdbc:mysql://localhost:3306/geladao_bebidas
spring.datasource.username=root
spring.datasource.password=2798
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG

jwt.secret=DJNwrPvXlB9VjjNM-EX--pFJg3PBKiYmICHunYnw1XtxOPGZXwC8xj0p6IL93w9E
jwt.expiration=86400000
